### PR TITLE
Added Italian language

### PR DESCRIPTION
**Pull request by RubensRainelli**
By Rubens Rainelli
https://rubensrainelli.t.me

### CODE REVIEW

**Comment by oleganza** [comment]
Hi Rubens! Thank you for the contribution, this is very helpful. We will check this patch and merge it in a few days. It will be under a feature flag in the Dev Menu until we cross-check the strings (there could be some missing translations, or some phrases may not fit) and then after polishing we'll enable it by default.

**Comment by voloshinskii** [comment]
Hi @RubensRainelli! Thank you again for your contribution

We made a language toggler in Dev Menu, it will be available for manual activation

**Comment by RubensRainelli** [comment]
Where's the dev menu? 😁

3 apr 2023 05:11:11 Max Voloshinskii ***@***.***>:

**Comment by voloshinskii** [comment]
@RubensRainelli 
You have to tap 5 times on the Tonkeeper logo on Settings screen

**Comment by RubensRainelli** [comment]
I've made 3.1 alignment @voloshinskii @oleganza

**Pull request merged**
