### PR TITLE
Release 3.6

### PR DESCRIPTION
**Pull request by sorokin0andrey**

### CODE REVIEW

**Review by voloshinskii — APPROVED** [review]

**Review by MariaBit — APPROVED** [review]

**Comment by PhoneNain** [comment]
flljl

**Comment by PhoneNain** [comment]
contact

**Comment by PhoneNain** [comment]
****

**Comment by PhoneNain** [comment]
**good luck **

**Comment by PhoneNain** [comment]
Use `git status` to list all new or modified files that haven't yet been committed.

**Pull request merged**
