### PR TITLE
release: 4.7.1

### PR DESCRIPTION
**Pull request by voloshinskii**

### CODE REVIEW

**Review by olyaMay — APPROVED** [review]

**Review by MariaBit — APPROVED** [review]

**Comment by JabulaniNgcobo** [comment]
#890

**Comment by JabulaniNgcobo** [comment]
#831

**Review by Kamikm — COMMENTED** [review]
0534666

**Comment by Kamikm** [comment]
> 0534666

**Review by Musta123445 — APPROVED** [review]

**Review by Musta123445 — APPROVED** [review]

**Comment by Mo8585** [comment]
I

**Pull request merged**
